vim.pack.add({ 'https://github.com/vague-theme/vague.nvim' })
vim.cmd.colorscheme('vague')

require("core.options")
require("core.keymaps")
require("core.autocmds")
require("plugins.blink")
require("plugins.mason")
require("plugins.ui")
require("plugins.mini")
require("plugins.conform")
require("plugins.goodies")
